USE kaivan_wileyedge;

-- #1 --
SELECT * FROM employee;

-- #2 --
SELECT first_name, last_name from employee;

-- #3 --
SELECT FIRST_NAME AS 'EMPLOYEE NAME' FROM EMPLOYEE;

-- #4 --
SELECT lower(LAST_NAME) AS LAST_NAME FROM EMPLOYEE; 

-- #5 --
SELECT UPPER(LAST_NAME) AS LAST_NAME FROM EMPLOYEE; 

-- #6 --
SELECT DISTINCT Departement FROM EMPLOYEE;

-- #7 --
SELECT substr(FIRST_NAME,1,4) FROM EMPLOYEE;

-- #8 --
SELECT POSITION('h' IN  'John') AS MatchPosition; 

-- SELECT @@version-- 

-- #9 --
SELECT RTRIM(FIRST_NAME) FROM EMPLOYEE;

-- #10 --
SELECT LTRIM(FIRST_NAME) FROM EMPLOYEE;

-- #11 --
SELECT FIRST_NAME, length(FIRST_NAME) FROM EMPLOYEE;

-- #12 --
SELECT replace(FIRST_NAME, 'o', '#') FROM EMPLOYEE;

-- #13 --
SELECT FIRST_NAME, year(Joining_date), month(Joining_date), day(Joining_date) FROM EMPLOYEE;

-- #14 --
SELECT * FROM EMPLOYEE order by FIRST_NAME;

-- #15 --
SELECT * FROM EMPLOYEE order by FIRST_NAME DESC;
 
 -- #16 --
SELECT * FROM EMPLOYEE order by FIRST_NAME, SALARY DESC;
 
 -- #17 --
SELECT * FROM EMPLOYEE WHERE FIRST_NAME = 'Bob';
  
  -- #18 --
SELECT * FROM EMPLOYEE WHERE FIRST_NAME = 'Bob' or FIRST_NAME = 'Alex' ;

-- #19 --
SELECT * FROM EMPLOYEE WHERE FIRST_NAME NOT IN ('Bob','Alex');

-- #20 --
SELECT * FROM employee WHERE FIRST_NAME LIKE 'J___';

-- #21 --
SELECT * FROM EMPLOYEE WHERE month(Joining_date) = '01';

-- #22 --
SELECT * FROM EMPLOYEE WHERE JOINING_DATE < '2019-03-01';
-- SELECT * FROM EMPLOYEE WHERE year(Joining_date) = '2019' AND month(Joining_date) < '03' AND day(Joining_date) > '01';--

-- #23 --
SELECT * FROM employee;
SELECT * FROM REWARD;

SELECT E.Employee_id, e.FIRST_NAME, e.JOINING_DATE, R.DATE_REWARD, DATEDIFF(r.DATE_REWARD, e.JOINING_DATE) AS 'DIFFERENCE IN DATES' FROM EMPLOYEE E, REWARD R WHERE E.Employee_id = R.Employee_ref_id;
SELECT E.Employee_id, e.FIRST_NAME, e.JOINING_DATE, R.DATE_REWARD, ABS(TIMESTAMPDIFF(DAY, r.DATE_REWARD, e.JOINING_DATE)) AS 'DIFFERENCE IN DATES' FROM EMPLOYEE E, REWARD R WHERE E.Employee_id = R.Employee_ref_id;
SELECT E.Employee_id, e.FIRST_NAME, e.JOINING_DATE, R.DATE_REWARD, ABS(TIMESTAMPDIFF(MONTH, r.DATE_REWARD, e.JOINING_DATE)) AS 'DIFFERENCE IN DATES' FROM EMPLOYEE E, REWARD R WHERE E.Employee_id = R.Employee_ref_id;
SELECT E.Employee_id, e.FIRST_NAME, e.JOINING_DATE, R.DATE_REWARD, ABS(TIMESTAMPDIFF(YEAR, r.DATE_REWARD, e.JOINING_DATE)) AS 'DIFFERENCE IN DATES' FROM EMPLOYEE E, REWARD R WHERE E.Employee_id = R.Employee_ref_id;